google_iam_binding_uses_role
JupiterOne/graph-google-cloud pull request #261
Opened 2021-07-14 23:07 UTC by mknoedel

2021-07-14 23:08 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +                  skipTargetCreation: false,
Do we want to skip target creation here? from the looks of it, the vast majority of iam_roles are not ingested by this integration. I think they are google managed or something like that.

2021-07-14 23:10 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +        if (binding.role) {
Do we need to account for project-level role names differently (ex: `projects/j1-gc-integration-dev-v3/roles/167984947943customrole`)? Not that I could tell from our test environment, but it was something that stood out as other bindings looked to be `groups/admin` and stuff like that.

2021-07-16 21:30 UTC, austinkelleher requested changes

2021-07-16 21:30 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +                  projectId,
We should probably remove this. I think that this role could be a custom role that exists as part of a child project that will get picked up later by another integration instance.

2021-07-16 21:30 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +                  skipTargetCreation: false,
Similar to above, I think we should create this target entity. This is likely a "custom" role owned by another child project integration instance.

2021-07-16 21:30 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +            await jobState.addRelationship(
Please make sure that we capture direct relationships to "managed" role entities.

2021-07-19 03:14 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +            await jobState.addRelationship(
Done by pulling this out into it's own step and then making it dependent on the role-fetching and creating steps.

2021-07-19 20:43 UTC, austinkelleher approved these changes
Amazing stuff! Super excited about these changes!

2021-07-19 20:43 UTC, merged