(DRAFT) INT-1155 binding assigned principal
JupiterOne/graph-google-cloud pull request #265
Opened 2021-07-16 19:23 UTC by mknoedel

(In the process of documenting)

2021-07-16 19:25 UTC, mknoedel commented on docs/jupiterone.md
> +| IAM Custom Role                                          | `google_iam_role`                                                 | `AccessRole`                       |
This change was due to incorrectly stating that the `IAM Managed Role` step was creating `google_iam_role` entities, which it was not, the `IAM Custom Role` and `IAM Bindings` do however but the documentation tool only allows for one step.

2021-07-16 19:25 UTC, mknoedel commented on docs/jupiterone.md
> +| `google_iam_binding`                                             | **USES**              | `google_iam_role`                                                 |
Forgot to add this in the previous PR

2021-07-16 19:52 UTC, mknoedel commented on src/getStepStartStates.ts
> +      : createStepStartState(ServiceUsageName.RESOURCE_MANAGER),
I believe we don't want to run this step when we are ingesting organization data.

The problem is that both `fetch-resource-manager-iam-policy` and `fetch-iam-bindings` ingest some roles, and roles => principal relationships, but `fetch-iam-bindings` ingests far more data (along with binding entities and their relationships) but requires Organization level permissions. Because of this, I think we don't want to run `fetch-resource-manager-iam-policy` in any google organization that has access to `fetch-iam-bindings`. The way I think this can be done is by checking the `configureOrganizationProjects` config variable.

2021-07-16 20:05 UTC, mknoedel commented on src/getStepStartStates.ts
> +      : createStepStartState(ServiceUsageName.CLOUD_ASSET),
(read the lower comment in this file first for context) Similar to my comment below, I think we only want to enable this step for one integration instance instead of all the project instances that get automatically created. 

This step also requires organization level permissions so we shouldn't try to run it on instances that aren't using `configureOrganizationProjects` I believe.

2021-07-16 20:20 UTC, mknoedel commented on src/getStepStartStates.ts
> +      : createStepStartState(ServiceUsageName.CLOUD_ASSET),
(read the lower comment in this file first for context) Similar to my comment below, I think we only want to enable this step for one integration instance instead of all the project instances that get automatically created.

This step also requires organization level permissions so we shouldn't try to run it on instances that aren't using configureOrganizationProjects I believe.

2021-07-16 20:24 UTC, mknoedel commented on src/steps/cloud-asset/constants.ts
> +  // 'google_domain', // These are getting ignored for now
I wasn't getting any of these and we weren't handling these cases in the `STEP_RESOURCE_MANAGER_IAM_POLICY` step, but [the google documentation](https://cloud.google.com/asset-inventory/docs/reference/rpc/google.iam.v1#google.iam.v1.Binding) says there is another level that represents "all the users of that domain. For example, google.com or example.com." 

I'm not sure how common these are, but skipping for this PR at least.

2021-07-16 20:25 UTC, mknoedel commented on src/steps/cloud-asset/constants.ts
> +);
In order to maintain backwards compatibility with `STEP_RESOURCE_MANAGER_IAM_POLICY` I'm creating role -> principal relationships here as well.

2021-07-16 20:26 UTC, mknoedel commented on src/steps/cloud-asset/index.test.ts
> +        collectedRelationships: context.jobState.collectedRelationships.length,
I don't think there is much value in storing hundreds of graph objects when the purpose of this test is higher level than that.

2021-07-16 20:27 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +
Safer to have this before any relationship creation I think

2021-07-16 20:28 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +        if (binding.members?.length) {
In a future PR, I think I'm going to break out each of these relationship branches to their own step, this one is getting quite large.

2021-07-16 20:34 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +      },
Comes from `findOrCreateIamRoleEntity` and is how this previously functioned. I believe we need to create these roles because we need to build mapped relationships off of this entity which is currently not supported by the persister. This may be causing duplicate role entities today though I'm not sure.

2021-07-16 20:36 UTC, mknoedel commented on src/steps/iam/index.ts
> +    entities: [],
This step only added data to the jobState, it didn't create entities.

2021-07-16 20:37 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> -export function createIamServiceAccountAssignedIamRoleRelationship(params: {
I deleted this method and it's associated tests because it was more confusing than it was worth I think.

2021-07-16 20:38 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
>  export function createGoogleWorkspaceEntityTypeAssignedIamRoleMappedRelationship({
Updated this method to work with both roles and bindings, the relationship direction stuff made it kind of dirty which I'm not happy about, but I couldn't think of a better way a the time.

2021-07-16 20:39 UTC, mknoedel commented on src/steps/resource-manager/index.ts
> -  const iamUserEntityWithParsedMember =
Took this function call out of this method to make it more pure and easier to reuse the conditional logic below.

2021-07-16 20:39 UTC, mknoedel commented on src/steps/resource-manager/index.ts
> -    const iamRoleEntity = await findOrCreateIamRoleEntity({
Same with this method.

2021-07-16 20:40 UTC, mknoedel commented on src/steps/resource-manager/index.ts
> +    if (!data.binding.role) {
This was needed once we upgraded the typings.

2021-07-16 20:41 UTC, mknoedel commented on src/steps/resource-manager/index.ts
> +    if (!data.binding.role) {
You can't build relationships to a role that doesn't exist.

2021-07-16 21:30 UTC, austinkelleher requested changes
Nice job!

2021-07-16 21:30 UTC, austinkelleher commented on src/steps/cloud-asset/index.test.ts
> +      // Each of these relationships could either be mapped or direct depending on if it has been previously ingested in this run so not checking if direct or mapped here
It would be great if we could add an assertion for both mapped and non-mapped, and that our recordings would include both cases to prevent later regression. Thanks for raising!

2021-07-19 03:57 UTC, mknoedel commented on src/steps/cloud-asset/index.test.ts
> +      // Each of these relationships could either be mapped or direct depending on if it has been previously ingested in this run so not checking if direct or mapped here
I made the scaffolding but didn't have examples right off the bat for these. I'll add these examples in a later PR when I get more familiar with the GCP platform.

2021-07-19 12:17 UTC, austinkelleher approved these changes
Thank you for all of your work on this!

2021-07-19 12:17 UTC, merged