binding to google_domain relationships
JupiterOne/graph-google-cloud pull request #272
Opened 2021-07-22 19:02 UTC by mknoedel

2021-07-22 19:05 UTC, mknoedel commented on src/steps/app-engine/__snapshots__/index.test.ts.snap
> -          "name": "austin.kelleher@jupiterone.dev",
The `name` and `displayName` properties are set to a different property in `graph-google` and I didn't want to overwrite correct name information: ex: "Michael Knoedel, with incorrect name information: ex: "michael.knoedel@jupiterone.com"

2021-07-22 19:07 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +                    relationshipDirection: RelationshipDirection.REVERSE,
Made this key required

2021-07-22 19:08 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> +  targetEntity: Partial<PrimitiveEntity>;
Pulled out targetEntity creation logic out of this method in order to simplify this method a bit.

2021-07-22 19:10 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> +    : [['_type', '_class', 'email']];
Optimization to only search on what you know the entity has access to.

2021-07-22 19:23 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> +  const targetKey = targetEntity._key ?? (targetEntity.email as string);
The closest thing we will have to a key is an email which is what we had used before, though part of me thinks it would be better to just let the mapper make the relationship key instead of passing in the email.

I believe if you don't give a _key property to a mapped relationship, the key of the target entity becomes `mapped_entity` or something like that.

2021-07-22 19:24 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> -      },
This all gets handled on a per-entity type basis now to prevent if statements everywhere.

2021-07-22 19:25 UTC, mknoedel commented on src/steps/resource-manager/createIamEntities.ts
> +// https://github.com/JupiterOne/graph-google/blob/ad4d88d0151cd7dc4ad93dc30d1aa40e6c97778e/src/steps/domains/converters.ts#L6
All of these methods were taken from the graph-google integration to ensure I'm not corrupting entity data if the mapped relationships hit existing entities.

2021-08-02 18:35 UTC, aiwilliams requested changes

2021-08-02 18:35 UTC, aiwilliams commented on src/steps/app-engine/__snapshots__/index.test.ts.snap
> +            "_class",
I think it would be good to drop this because `_type: 'google_user'` is very specific, and not including `_class` makes it so that we can change/add/remove values in the future without consequence (in terms of target resolution).

2021-08-02 18:35 UTC, aiwilliams commented on src/steps/resource-manager/converters.ts
> +    ? [['_key']]
I think it'd be good to make this `[_type, _key]` so that at some point when we have the optimization of finding a specific, single entity using an index on those two properties, this will benefit.

2021-08-02 18:35 UTC, aiwilliams commented on src/steps/resource-manager/converters.ts
> +    : [['_type', '_class', 'email']];
Can drop `_class` because `_type` is specific enough.

2021-08-02 18:35 UTC, aiwilliams commented on src/steps/resource-manager/converters.ts
> +  const targetKey = targetEntity._key ?? (targetEntity.email as string);
I wonder what the behavior is when we specify a target entity _key and other integrations attempt to do the say, but disagree on what the value should be?

2021-08-02 18:35 UTC, aiwilliams commented on src/steps/resource-manager/createIamEntities.ts
> +// https://github.com/JupiterOne/graph-google/blob/ad4d88d0151cd7dc4ad93dc30d1aa40e6c97778e/src/steps/domains/converters.ts#L6
🔥

2021-08-02 19:56 UTC, mknoedel commented on src/steps/resource-manager/converters.ts
> +  const targetKey = targetEntity._key ?? (targetEntity.email as string);
After a long search, it looks like _key and _type values will never be overwritten by the mapper - https://github.com/JupiterOne/jupiter-mapper/blob/main/src/engine/BuildPlan/PropertyMerger.ts#L119

2021-08-02 21:34 UTC, aiwilliams approved these changes

2021-08-02 21:35 UTC, merged