Create IAM bindings to cloud projects
JupiterOne/graph-google-cloud pull request #279
Opened 2021-07-30 23:31 UTC by mknoedel

The issue here is that we use the project name as the `google_cloud_project`s key which is not always available in the Google resource identifier. The identifier could represent either the name or the id of the project and it is up to us to figure out which one. Luckily, we ingest every cloud project earlier on in the integration run, so we can just use data from that step as a reference when making the binding mapped relationships to cloud projects.

2021-07-30 23:34 UTC, mknoedel commented on src/steps/cloud-asset/index.test.ts
> -        google_iam_binding_allows_ANY_RESOURCE,
renamed this key to be specific resources instead of have a type of "ANY_RESOURCE". "ANY_RESOURCE" is still used for documentation though.

2021-07-30 23:34 UTC, mknoedel commented on src/steps/cloud-asset/index.test.ts
> +        'google_iam_binding_allows_cloud_project',
projects are always mapped when doing organization ingestion.

2021-07-30 23:38 UTC, mknoedel commented on src/steps/cloud-asset/__recordings__/createMappedBindingAnyResourceRelationships_3853245014/recording.har
> +      {
Don't know why this was added, but it does return data, so I'm just going to leave it in 🙃

2021-07-30 23:39 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +            context,
Needed to add context so the keyGen methods could have access to the jobState.

2021-07-30 23:40 UTC, mknoedel commented on src/utils/iamBindings/findResourceKindFromCloudResourceIdentifier.test.ts
>    [`//cloudresourcemanager.googleapis.com/projects/${TEST_PROJECT_ID}`]:
Because a project identifier could be either a projectName or a projectId, I needed to make sure that I had a test for both cases.

2021-07-30 23:43 UTC, mknoedel commented on src/utils/iamBindings/typeToKeyGeneratorMap.ts
> +    )) ?? finalIdentifierKeyMap(id),
This logic searches the jobState in the `projectId` map to get it's related name. If the identifier is in fact a name, it will not be found in the `projectId` map, so we can just use it as is.

2021-07-30 23:44 UTC, mknoedel commented on src/utils/jobState.ts
> +  await jobState.setData(`projectId:${project.projectId}`, project.name);
Need to support both maps for various reasons. IMHO, we should just be using the projectId as the `_key` instead of the name as it is more unique.

2021-08-02 18:58 UTC, aiwilliams requested changes

2021-08-02 18:58 UTC, aiwilliams commented on src/steps/cloud-asset/index.ts
>                    _type: type,
Note: `_type` cannot be specified in the case that the `targetEntity` is a SQL database.

2021-08-02 19:00 UTC, austinkelleher requested changes

2021-08-02 19:05 UTC, aiwilliams commented on src/utils/jobState.ts
> +  await jobState.setData(`projectId:${project.projectId}`, project.name);
It would seem worthwhile to move toward using the `projectId`, perhaps in another PR after considering the implications.

2021-08-02 19:15 UTC, mknoedel commented on src/steps/cloud-asset/__recordings__/createMappedBindingAnyResourceRelationships_3853245014/recording.har
> +            "text": "{\"error\":{\"code\":401,\"message\":\"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See h
The credentials we have in the test account don't allow us to fetch projects so when `fetchResourceManagerProject` is called, it fails the API call. However,  `fetchResourceManagerProject` makes a shell project entity even on api failures. I can then use to check mapped relationships against for my test. 

It isn't important that the project is pulled from the api for this test, only that the entity is in the job state, so I think it is ok to leave this recording in here.

2021-08-02 20:40 UTC, austinkelleher approved these changes

2021-08-02 21:34 UTC, aiwilliams approved these changes

2021-08-02 21:39 UTC, aiwilliams approved these changes

2021-08-02 21:45 UTC, merged