Make permissions a string as it is too big
JupiterOne/graph-google-cloud pull request #288
Opened 2021-08-13 18:41 UTC by mknoedel

This is a breaking change for queries on this key. There are no managed questions that use this key.

Users can still query for a specific permission via `find google_iam_role with permission~={{PERMISSION_NAME}}`, but this query will likely be quite slow (though I haven't benchmarked it) so it should likely be used only on an investigatory basis.

Permissions are already analyzed to create binding ALLOWS resource relationships so it is unlikely that a specific permission will need to be queried for.

2021-08-13 18:54 UTC, aiwilliams requested changes

2021-08-13 18:54 UTC, aiwilliams commented on CHANGELOG.md
> +  array.
It's helpful to form these as complete sentences when bringing them into release notes. Additionally, I think it's valuable to consider expressing the impact on users.

```
- Changed `google_iam_bindings.permissions: string[]` to `google_iam_bindings.permissions: string` due to
  limitations on `string[]` property lengths in JupiterOne. Queries will need to be changed from .... to ....
```

2021-08-13 18:55 UTC, aiwilliams commented
> Users can still query for a specific permission via find google_iam_role with permission~={{PERMISSION_NAME}}, but this query will likely be quite slow

The use of the includes matcher, `~=`, is promoted in a number of queries, so I think it's fine to recommend.

2021-08-13 20:30 UTC, mknoedel commented on CHANGELOG.md
> +  array.
Sounds good to me going forward to put more context into the CHANGELOG. I've kept it brief for most of my changes in the past, but I can definitely see 

> > Users can still query for a specific permission via find google_iam_role with permission~={{PERMISSION_NAME}}, but this query will likely be quite slow
> 
> The use of the includes matcher, `~=`, is promoted in a number of queries, so I think it's fine to recommend.

Works for me, I wasn't aware if there were query speed differences or not.

2021-08-13 20:31 UTC, mknoedel commented
> > Users can still query for a specific permission via find google_iam_role with permission~={{PERMISSION_NAME}}, but this query will likely be quite slow
> 
> The use of the includes matcher, `~=`, is promoted in a number of queries, so I think it's fine to recommend.

Works for me, I wasn't aware if there were query speed differences or not.

2021-08-13 21:06 UTC, aiwilliams approved these changes
Looks good to me! I think it a good idea to get @austinkelleher's input on this one, as you suggested in Slack.

2021-08-16 16:13 UTC, austinkelleher approved these changes

2021-08-16 16:15 UTC, merged

2021-08-23 14:34 UTC, aiwilliams commented
Created https://jupiterone.atlassian.net/browse/CORE-1470 to get the persister to let us know.