Initial network ingestion
JupiterOne/graph-google-cloud pull request #30
Opened 2020-10-03 18:58 UTC by austinkelleher

2020-10-03 19:36 UTC, erkangz requested changes

2020-10-03 19:36 UTC, erkangz commented on src/utils/firewall.ts
> +      } else if (isHost(ipRange)) {
```suggestion
      } else if (isHost(ipRange)) {
        if (isPublicIp(ipRange)) {
          await callback({
            targetFilterKeys: [['_class', 'publicIpAddress']],
            targetEntity: {
              _class: 'Host',
              publicIpAddress: ipRange.split('/')[0],
            },
            properties: relationshipProperties,
          });
        }
        else {
          await callback({
            targetFilterKeys: [['_class', 'privateIpAddress']],
            targetEntity: {
              _class: 'Host',
              privateIpAddress: ipRange.split('/')[0],
            },
            properties: relationshipProperties,
          });
        }
      } else {
        await callback({
          targetFilterKeys: [['_class', 'CIDR']],
          targetEntity: {
            _class: 'Network',
            CIDR: ipRange,
            netmask: ipRange.split('/')[1],
          },
          properties: relationshipProperties,
        });
      }
```

2020-10-03 19:40 UTC, erkangz requested changes

2020-10-03 19:40 UTC, erkangz commented on terraform/compute_vms.tf
> +  target_tags = ["https"]
should this be `"ssh"`?

2020-10-04 18:10 UTC, ndowmon commented on src/steps/compute/constants.ts
> +// Entities
Not necessary, but it would have been nice to have updated this `constants.ts` file to match the newer style of entity/relationship definitions (using `StepEntityMetadata` and `StepRelationshipMetadata`)

2020-10-04 18:43 UTC, ndowmon reviewed
Looks good @austinkelleher. I left a few notes.

2020-10-04 18:43 UTC, ndowmon commented on src/steps/compute/constants.ts
> +// Entities
Not necessary, but it would have been nice to have updated this `constants.ts` file to match the newer style of entity/relationship definitions (using `StepEntityMetadata` and `StepRelationshipMetadata`)

2020-10-04 18:43 UTC, ndowmon commented on src/steps/compute/converters.ts
> +         * traffic to an instance&#39;s external IP address because service
```suggestion
         * traffic to an instance's external IP address because service
```

2020-10-04 18:43 UTC, ndowmon commented on src/steps/compute/index.ts
> +    const subnetEntity = await jobState.findEntity(subnetwork);
I noticed that this addition added two steps to the `dependsOn` of `fetchComputeInstances`-  `STEP_COMPUTE_NETWORKS` _and_ `STEP_COMPUTE_SUBNETWORKS`.

Can a `google_compute_network` have a `google_compute_instance`, or can only a `google_compute_subnetwork` have a `google_compute_instance`?

2020-10-04 18:43 UTC, ndowmon commented on terraform/output.tf
> +output "public_vm_external_ip" {
What's the point of these outputs? Maybe I missed something but I didn't see them referenced. Also, does it make sense to put these in an `output.tf` file, or to output them from `compute_vms.tf` where they are generated?

2020-10-05 12:13 UTC, austinkelleher commented on terraform/output.tf
> +output "public_vm_external_ip" {
I mainly did this so that I would get a nice log output at the end of my terraform apply with the public IP so I could test it out.

2020-10-05 12:17 UTC, austinkelleher commented on src/steps/compute/constants.ts
> +// Entities
Agreed. Going to do this in bulk separately.

2020-10-05 22:42 UTC, erkangz approved these changes

2020-10-05 23:35 UTC, merged