Create Api Service HAS Any Resource relationships
JupiterOne/graph-google-cloud pull request #333
Opened 2021-10-01 22:08 UTC by mknoedel

Right now, we are only able to do analysis of the roles attached directly to Google Cloud resources. We need to connect those resources to the projects so we can analyze the roles on the project, folder and org levels as well.

#### Why not connect resources to their projects directly instead of going through the Api Service first?

In order to facilitate a better user experience with the front-end node expansion functionality:
![image](https://user-images.githubusercontent.com/25489482/135691119-02a27476-e29b-4a76-82ed-26a5606fd099.png)
... we don't want to have too many things attached to the project as it would get unruley very fast. It is a bit cleaner to attach it to the api service instead. Plus, that is what Google Cloud does anyway according to their Resource Hierarchy graph:
![image](https://user-images.githubusercontent.com/25489482/135691268-11aa9616-a16c-4808-955e-2dc6011c815d.png)

2021-10-03 15:57 UTC, austinkelleher requested changes
Looks good! Left some suggestions.

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +          (bindingEntity.projectId ?? bindingEntity.projectName) +
Let's create a function to help clean this up a bit. You can also remove the `else` and re-use a calculated resource key.

Consider something like:

```typescript
const resourceKey = buildBindingEntityResourceKey(bindingEntity);

if (projectToResourceTracker.has(resourceKey)) return;
projectToResourceTracker.add(resourceKey);
```

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +export async function createApiServiceToAnyResourceRelationships(
Overall I think the logic in this function looks good, but there is a lot going on. Can we split this up into a few smaller functions?

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +        ].includes(resourceType!)
```ts
if (isOrganizationalHierarchyResource(resourceType)) {

}
```

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +        const serviceKey =
```ts
const serviceGraphObjectKey = buildServiceGraphObjectKeyFromBindingEntity(bindingEntity);
```

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +          resourceType === MULTIPLE_J1_TYPES_FOR_RESOURCE_KIND ||
I remember this being an issue, but I'm a bit fuzzy on the conclusion of whether this is permanent. Can you elaborate on whether this is permanent or not? If it's not permanent, can you explain how we can get rid of this?

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +            ? createDirectRelationship({
We seem to have this type of conditional logic inside of the project a lot. It would be nice if we introduced a `createDirectOrMappedRelationship` function. Doesn't have to happen in this PR, but it would help clean up code like this.

Example:

```ts
await jobState.addRelationship(
  createDirectOrMappedRelationship({
  
  })
);
```

2021-10-03 15:57 UTC, austinkelleher commented on src/steps/cloud-asset/index.ts
> +                 * The mapper does properly remove mapper-created entities at the moment. These
`"does not properly"`?

2021-10-04 15:19 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +          resourceType === MULTIPLE_J1_TYPES_FOR_RESOURCE_KIND ||
The issue here is the way that we modeled sql instances is not 1 to 1 with our `_type`s. A Google Resource Type of `sqladmin.googleapis.com/Instances` could be `google_sql_mysql_instance`, `google_sql_postgres_instance`, or `google_sql_sql_server_instance` and I'm not sure of any way to know which one it is. 

In order to fix this, we will have to change these types.

2021-10-04 15:23 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +            ? createDirectRelationship({
Totally agree. I think this makes sense as a cleanup effort in another PR as it would likely want to use this pattern in many places and I'm worried it would muddle this PR.

2021-10-04 15:31 UTC, mknoedel commented on src/steps/cloud-asset/index.ts
> +            ? createDirectRelationship({
I tried making this method, but it ended up seeming a bit more cumbersome than helpful. I still need to put the conditional logic somewhere in order to generate the targetEntity properly for the mapped relationship. I think the reason why this Direct or Mapped logic looks confusing is because of the large comment over skipTargetCreation.

2021-10-04 15:36 UTC, austinkelleher approved these changes

2021-10-04 15:39 UTC, merged