Improve experience of '403: Caller does not have permission' error
JupiterOne/graph-google-cloud pull request #46
Opened 2020-12-10 22:14 UTC by ndowmon

2020-12-10 22:36 UTC, aiwilliams requested changes

2020-12-10 22:36 UTC, aiwilliams commented on src/steps/resource-manager/index.ts
> +      `${JSON.stringify({ code: err.code, message: err.message })}`;
Not a big deal at this time, but for consistency sake and so that others are aware and we can work toward a solution over time, I'll point out the formatting of [messages from the SDK](https://github.com/JupiterOne/sdk/blob/8ff1018a6abceb131bf0c398aaa49ac43d4cc5e3/packages/integration-sdk-runtime/src/execution/__tests__/dependencyGraph.test.ts#L649). I think we'll need to work toward an API where we can provide a message and "parenthetical" properties (as well as `error: true`!) that are stored with the event and that are consistently presented by the job log UI.

2020-12-10 22:36 UTC, aiwilliams commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
I'd like to see all job event names match the pattern of lower snake case. Until this project, none others were using this form.

2020-12-10 22:36 UTC, aiwilliams commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
Also, note that anything that matches `/error/i` will mark the job as `errorsOccurred`. `*_failure` does not. 😢  This is why we need an API where we send the event as `error: true` (probably would be good to have `warn: true` as well, or `level: 'info' | 'warn' | 'error'`).

2020-12-10 22:57 UTC, ndowmon commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
I have heard you mention that about `error` vs `failure`. Seems like regexing `/error/i` out of a job log is not the most foolproof way to identify if an error occurred...

```bash
2020-12-10-17-56-30UTC [step-success] Step "fetch-system-errors" completed successfully"
```

2020-12-10 22:58 UTC, ndowmon commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
To be clear, your requested change is to downcase `get_project_forbidden_error` and `get_project_error`?

2020-12-11 01:38 UTC, aiwilliams commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
> I have heard you mention that about `error` vs `failure`. Seems like regexing `/error/i` out of a job log is not the most foolproof way to identify if an error occurred...

Definitely not foolproof! I think that code is nearly 3 years old 😳

2020-12-11 01:42 UTC, aiwilliams commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
> To be clear, your requested change is to downcase `get_project_forbidden_error` and `get_project_error`?

I didn't think beyond the case at the time of my comment, but now I wonder if we should call these `auth_error` events? It could be worthwhile to search for calls to `publishEvent` for a survey of names. The key point here is, I think we want to end up with a common set of event names. What do you thing?

2020-12-11 13:14 UTC, ndowmon commented on src/steps/resource-manager/index.ts
> +        name: 'GET_PROJECT_FORBIDDEN_ERROR',
I agree. And I don't really like the names I had initially given, they are too specific.

2020-12-11 13:38 UTC, aiwilliams approved these changes

2020-12-11 13:38 UTC, aiwilliams commented on CHANGELOG.md
> +  to access the `/v1/projects/{projectId}` endpoint.
🔥

2020-12-11 14:13 UTC, aiwilliams approved these changes

2020-12-11 14:50 UTC, merged