AB#2089 handle errors in step handler functions
JupiterOne/graph-google-cloud pull request #51
Opened 2021-01-05 00:00 UTC by mknoedel

Add error handling and handle billing configuration errors outside of Sentury

2021-01-05 00:39 UTC, aiwilliams reviewed
Needs a `CHANGELOG.md` update.

2021-01-05 00:39 UTC, aiwilliams commented on src/utils/withErrorHandling.test.ts
> +  });
This can be achieved with Jest:
```suggestion
  const executionHandler = jest.fn().mockRejectedValue(
    new Error('This API method requires billing to be enabled. Please enable billing on project #545240943112 by visiting https://console.developers.google.com/billing/enable?project=545240943112 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.'));
```

2021-01-05 00:39 UTC, aiwilliams commented on src/utils/withErrorHandling.test.ts
> +  }
With Jest, this can be:
```suggestion
  await expect(handledThrowerFunction(fakeContext))
    .rejects.toThrow(IntegrationValidationError);
```

2021-01-05 01:52 UTC, austinkelleher reviewed
Besides the testing comments that Adam mentioned, this looks great! Thanks for the fixes.

2021-01-05 13:48 UTC, ndowmon commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
This feels like a pretty broad stroke to take, wrapping each execution handler with `withErrorHandling()`. I imagine that these errors matching `/requires\sbilling/` can be isolated to the API calls... why not handle this case in `src/google-cloud/client.ts` instead?

2021-01-05 14:42 UTC, mknoedel commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
From the logs, it looks like every step is throwing this error which means we are seeing it 6 times on every integration run. I believe this is a standard pattern for google apis so we likely want to handle it for every api call.

also from what I've seen, we aren't handling many errors in this project which means whenever there is an error thrown anywhere, it gets posted to the job log as a scary "Unexpected Error has occurred" and also gets sent to Sentry. I think it makes sense to have each integration handle their own errors and this gives us a common place to do so.

2021-01-05 15:49 UTC, aiwilliams commented on src/utils/withErrorHandling.test.ts
> +  }
Did this not work out after all?

2021-01-05 15:49 UTC, aiwilliams commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
I understand where you're coming from @ndowmon, having had a similar feeling when I reviewed the code. I think it could be fine to do it this way (perhaps we need an `onStepFailure` callback for invocation configs so we don't have to wrap the `executionHandler` everywhere), though it is worth documenting the reason that the API client doesn't handle this, since the pattern we've been pursuing is one where the clients know the nuances of the API responses. There is an [`IntegrationProviderAuthorizationError`](https://github.com/JupiterOne/sdk/blob/8a3c4bea6b65fc8819a0208018443d69a6628796/packages/integration-sdk-core/src/errors.ts#L224) that can be thrown from the client and it will be shown to the user. It may be that the client in this project needs to be refactored to wrap the calls.

2021-01-05 18:10 UTC, austinkelleher submitted a review, later dismissed

2021-01-05 19:18 UTC, aiwilliams commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
Another thought that came to me... The [`IntegrationValidationError`](https://github.com/JupiterOne/sdk/blob/8a3c4bea6b65fc8819a0208018443d69a6628796/packages/integration-sdk-core/src/errors.ts#L159) is documented and intended to be thrown from the `validateInvocation` function, so it may lead to confusion to throw it from not that function.

Seems this is an authorization error, not an authentication one and not a validation one.

Sorry for the late comment, but figured it would be helpful for consistency and clarity 😁

2021-01-05 19:28 UTC, ndowmon commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
@aiwilliams: Michael and I had a call this morning about the design here. I think he's working on some of these changes

2021-01-05 19:51 UTC, mknoedel commented on src/utils/withErrorHandling.ts
> +export function withErrorHandling(
Yeah I agree and switched it to an authorization error. Good catch @aiwilliams thanks!

2021-01-05 19:58 UTC, mknoedel commented on src/utils/withErrorHandling.test.ts
> +  });
That does work thanks!

2021-01-05 20:20 UTC, ndowmon requested changes

2021-01-05 20:20 UTC, ndowmon commented on src/google-cloud/client.test.ts
> +  test('should throw an IntegrationValidationError when a billing message is error is thrown', async () => {
Can you update the name of this test? It now checks for `IntegrationProviderAuthorizationError`, not `IntegrationValidationError`.

2021-01-05 20:20 UTC, ndowmon commented on src/google-cloud/client.test.ts
> +  test('should throw an IntegrationValidationError when another billing message is error is thrown', async () => {
You'll want to update the name of this test as well.

2021-01-05 20:20 UTC, ndowmon commented on src/google-cloud/client.test.ts
> +  test('should throw an IntegrationError on all other unhandled errors', async () => {
Should be `IntegrationProviderAPIError`, not `IntegrationError`

2021-01-05 20:20 UTC, ndowmon commented on src/google-cloud/client.ts
> +        throw new IntegrationProviderAuthorizationError(error.message);
Check out the signature of `IntegrationProviderAuthorizationError` and `IntegrationProviderApiError` in the sdk: https://github.com/JupiterOne/sdk/blob/master/packages/integration-sdk-core/src/errors.ts#L182

Not sure if you have access to the endpoint at this level. May need to find a way to access that. @austinkelleher are the endpoint paths accessible?

```typescript
export declare class IntegrationProviderAuthorizationError extends IntegrationError {
    constructor(options: {
        cause?: Error;
        endpoint: string;
        status: string | number;
        statusText: string;
        resourceType?: string[];
    });
}

export declare class IntegrationProviderAPIError extends IntegrationError {
    constructor(options: {
        cause?: Error;
        endpoint: string;
        status: string | number;
        statusText: string;
    });
}
```

2021-01-07 14:27 UTC, mknoedel commented on src/utils/withErrorHandling.test.ts
> +  }
This did work, just forgot to resolve

2021-01-09 02:12 UTC, aiwilliams submitted a review, later dismissed
Thanks for the thorough tests 👍

2021-01-11 15:09 UTC, ndowmon reviewed
Looks good. Can you just type the `createErrorProps` function before merging?

2021-01-11 15:09 UTC, ndowmon commented on src/google-cloud/client.ts
> +  const chillMessageStrings = [
This isn't a big deal but I probably would have called this `disabledBillingMessageStrings` or `errorMessagesToKeep` if we want it to be more generic.

2021-01-11 15:16 UTC, mknoedel commented on src/google-cloud/client.ts
> +  const chillMessageStrings = [
I'll update that

2021-01-11 18:44 UTC, mknoedel commented on test/recording.ts
> +    directory: __dirname,
Yeah, that makes sense, I'll add a parameter to allow a user to pass in a directory if they prefer.

2021-01-11 19:00 UTC, ndowmon approved these changes

2021-01-11 19:52 UTC, austinkelleher approved these changes

2021-01-11 19:54 UTC, merged