feat(INT-5917): add cloud function storage bucket relationship
JupiterOne/graph-google-cloud pull request #554
Opened 2022-11-04 15:14 UTC by gastonyelmini

## Context

Adds Google Cloud Functions Source Repository Relation.

![Captura de Pantalla 2022-11-04 a la(s) 10 51 14](https://user-images.githubusercontent.com/13191932/200010050-074c4def-c737-4bdd-a1ee-a00f4b12b965.png)

2022-11-04 15:22 UTC, gastonyelmini commented on src/steps/functions/index.ts
> +      const storageBucketKey = cloudFunction?.sourceArchiveUrl?.split('/')[2];
`soruceArchivrUrl` would be something like `gs://[bucket-id]/[file-name]`.

2022-11-04 16:11 UTC, i5o commented
Looking at the build result it looks like you forgot to add this step to the getStepStartSteps; just a heads up

2022-11-04 16:13 UTC, i5o commented on src/steps/functions/index.ts
> +      STEP_CLOUD_STORAGE_BUCKETS,
It would be great to also port this to the new constants we use

2022-11-04 16:14 UTC, i5o commented on src/steps/functions/index.ts
> +            _class: RelationshipClass.USES,
```suggestion
            _class: FunctionsRelationshipsSpec.GOOGLE_CLOUD_FUNCTION_USES_STORAGE_BUCKET._class
```

2022-11-04 16:15 UTC, i5o commented on src/steps/functions/constants.ts
> +    targetType: 'google_storage_bucket',
```suggestion
    sourceType: FunctionEntitiesSpec.CLOUD_FUNCTION._type,
    targetType: CLOUD_STORAGE_BUCKET_ENTITY_TYPE
```

2022-11-04 17:15 UTC, i5o commented on src/steps/functions/index.test.ts
> +    if (recording) await recording.stop();
recording gets defined on each test, why is this if required?

2022-11-04 17:17 UTC, i5o commented on src/steps/functions/index.test.ts
> +    if (recording) await recording.stop();
nvm - this is on the tests I made as well, could you check if this is required anyway?

2022-11-05 00:45 UTC, i5o approved these changes
Looks like you figured it out already :)
Thank you

2022-11-07 14:30 UTC, ndowmon commented on src/steps/functions/index.test.ts
> +import { storageTempNewAccountConfig } from '../storage/index.test';
Typically, credentials should be loaded from a top-level like `./test/config`. Can you explain why these credentials are loaded from the `storage` service?

2022-11-07 14:34 UTC, ndowmon commented on src/steps/functions/index.test.ts
> +      };
I would recommend implementing a pattern like what's used in `graph-aws` to get the step test config: https://github.com/JupiterOne/graph-aws/blob/main/test/config.ts#L69-L78

2022-11-07 14:52 UTC, ndowmon commented on src/steps/functions/index.ts
> +      const storageBucketKey = cloudFunction?.sourceArchiveUrl?.split('/')[2];
Interesting... note that the spec references the `google_cloud_function.buildConfig.source.storageSource` property for the relationship target here. I just reviewed the Google Cloud documentation, and it appears that `buildConfig` is a property on the `v2` API response (https://cloud.google.com/functions/docs/reference/rest/v2/projects.locations.functions#Function), but not on the `v1` API response (https://cloud.google.com/functions/docs/reference/rest/v1/projects.locations.functions#CloudFunction).

I think `buildConfig.source.storageSource` might have been an actual storage bucket key, and I didn't realize that we had already ingested the v1 API when building this spec. This exposes a tricky challenge for us - how can we migrate to the most up-to-date API responses in google cloud? 

Not something that needs to be addressed now, but let's start thinking about it.

```ts
  {
    /**
     * PROPERTY: google_cloud_function.buildConfig.source.storageSource
     * PATTERN: Build Child Relationships
     * REQUIRED PERMISSIONS: n/a
     */
    id: 'build-cloud-function-storage-bucket-relationships',
    name: 'Build Cloud Function -> Storage Bucket Relationships',
    entities: [],
    relationships: [
      {
        _type: 'google_cloud_function_uses_storage_bucket',
        _class: RelationshipClass.USES,
        sourceType: 'google_cloud_function',
        targetType: 'google_storage_bucket',
      },
    ],
    dependsOn: ['fetch-cloud-functions', 'fetch-cloud-storage-buckets'],
    implemented: true,
  },
```

2022-11-08 18:13 UTC, gastonyelmini commented on src/steps/functions/index.test.ts
> +import { storageTempNewAccountConfig } from '../storage/index.test';
I moved them to the config file, I can see that this are placed in some test because some recordings are pointing to organization/v2. Maybe we could refactor this recordings too in some other pr.

2022-11-08 18:14 UTC, gastonyelmini commented on src/steps/functions/index.ts
> +      const storageBucketKey = cloudFunction?.sourceArchiveUrl?.split('/')[2];
Good catch, something to take into account for future migrations

2022-11-08 22:51 UTC, ndowmon approved these changes

2022-11-09 00:24 UTC, i5o requested changes

2022-11-09 00:24 UTC, i5o commented on src/steps/functions/constants.ts
>      targetType: 'google_cloud_source_repository',
```suggestion
    targetType: CloudSourceRepositoriesEntitiesSpec.REPOSITORY._type,
```

2022-11-09 00:24 UTC, i5o commented on src/steps/functions/constants.ts
> +    targetType: 'google_storage_bucket',
```suggestion
    targetType: CLOUD_STORAGE_BUCKET_ENTITY_TYPE
```

2022-11-09 01:45 UTC, i5o approved these changes

2022-11-09 02:26 UTC, merged

2022-11-09 13:54 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v2.20.0`](https://github.com/JupiterOne/graph-google-cloud/releases/tag/v2.20.0) :rocket: