INT-8705: avoid extra inventory calls if api is disabled
JupiterOne/graph-google-cloud pull request #618
Opened 2023-07-25 13:25 UTC by gastonyelmini

Avoid making extra api calls if inventory api is disabled. Iterating thought a large amount of compute instances and trying to fetch instance inventory with the API disabled generates alerts in the dashboard.

2023-07-26 20:59 UTC, mishelashala requested changes

2023-07-26 20:59 UTC, mishelashala commented on src/steps/compute/index.ts
> +      if (computeInstance.zone && !inventoryApiDisabled) {
since this is a "fix", can we add a unit test?

2023-07-26 22:29 UTC, gastonyelmini commented on src/steps/compute/index.ts
> +      if (computeInstance.zone && !inventoryApiDisabled) {
I didn't find a good way to test the sdk implementation but will try.

2023-08-01 15:00 UTC, merged

2023-08-01 15:06 UTC, j1-internal-automation commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: PR was released in [`v2.30.3`](https://github.com/JupiterOne/graph-google-cloud/releases/tag/v2.30.3) :rocket: